Added zip and GNU parallel validations.

diff --git a/zip_dirs b/zip_dirs
--- a/zip_dirs
+++ b/zip_dirs
@@ -1,9 +1,9 @@
 #!/bin/bash
 # Zip directory into its own zip file.
-# TODO: chech parallel is installed.
-# TODO: chech zip is installed.
 # TODO: write help.
 
+command -v zip >/dev/null 2>&1 || { echo >&2 "I require zip but it's not installed.  Aborting."; exit 1; }
+command -v parallel >/dev/null 2>&1 || { echo >&2 "I require GNU parallel but it's not installed.  Aborting."; exit 1; }
 
 read -p "Zip each directory in the current location. Do you want to continue [y,N]? " -n 1 -r
 echo
diff --git a/zip_shp b/zip_shp
--- a/zip_shp
+++ b/zip_shp
@@ -1,8 +1,10 @@
 #!/bin/bash
 
 # zip the shapefiles in the given directory into their own zip file.
-# TODO: test parallel is installed.
 # TODO: write help message.
+
+command -v zip >/dev/null 2>&1 || { echo >&2 "I require zip but it's not installed.  Aborting."; exit 1; }
+command -v parallel >/dev/null 2>&1 || { echo >&2 "I require GNU parallel but it's not installed.  Aborting."; exit 1; }
 
 read -p "Zip each shapefile in the current location. Do you want to continue [y,N]? " -n 1 -r
 echo
